apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bmi
  template:
    metadata:
      labels:
        app: bmi
    spec:
      containers:
      - name: bmi
        image: bmi-app:latest  # <-- replace with your built image
        ports:
        - containerPort: 5000
