apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bmi
  template:
    metadata:
      labels:
        app: bmi
    spec:
      containers:
      - name: bmi
        image: bmi-app:latest
        imagePullPolicy: Never   # use local docker image if in minikube
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: bmi-service
spec:
  type: NodePort
  selector:
    app: bmi
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
